### ISSUE TITLE
Capo limits are not restored

### ISSUE THREAD

**Issue by piroxiljin** [BespokeSynth/BespokeSynth#1176] opened 2023-02-23 09:16 UTC
## Describe the bug

After restoring the session the value of the slider in the capo node becomes capped with default limits.

My drum pads send notes in range 36-43. While drumsynth requires notes from zero 0. I decided to shift notes with the help of capo. By default its slider has limits -12 - +12 semitones. But I need to subtract 36 semitones. So, I just reduced lower limit of the slider to -36.

I have played some time, and saved the session. But then, I have restored the session and limit of the capo slider was set to default -12 - +12, and value was set to -12 instead of -36.

I suppose capo slider forget to save or restore it's limits.

## Build info

bespoke 1.1.0 (Nov 16 2021 11:41:32) - Windows 7 - main bd41884b9

## Steps To Reproduce

* start a new patch
* insert the capo node
* change the limits of its slider 
  * hold ctrl, click left part of the slider
  * enter -30
* change the value of the slider: -30
* save the session
* reload the saved session

## Expected vs. actual behavior

Expected: value of the capo slider restored as -30. Limits of the slider also restored

Actually slider limits reset to default. Value is capped with the limit: -12

**Comment by crshrprt** [comment] 2023-02-23 10:37
Not a fix for the bug, but in the meantime you can use noteoctaver set to -3.

**Comment by piroxiljin** [comment] 2023-02-23 13:03
Thanks, for the workaround. So, if need to adjust more than 12 semitones we can combine a capo and an octaver. Octaver move by 12 semitones and then fine tune with with capo.

**Comment by NoxyNixie** [comment] 2023-02-24 02:33
I am unable to reproduce this in the latest Nightly build (https://github.com/BespokeSynth/BespokeSynth/releases/tag/Nightly).

![image](https://user-images.githubusercontent.com/211381/221077614-05a54d16-b92f-4beb-95c8-cb86746615e8.png)
This is after completely closing Bespoke and loading it.

For reference this was fixed in: 2d45e45ad5dde52df5351a0e812ecb53c2c78b4f

**Closed as completed by NoxyNixie** 2023-02-24 02:33 UTC
Labels: bug
