### ISSUE TITLE
Bug - connections from midi controllers don't save with project when they go outside of a prefab

### ISSUE THREAD

**Issue by PowerUser64** [BespokeSynth/BespokeSynth#1137] opened 2023-02-03 09:18 UTC
## Describe the bug

Connections from midi controllers don't save with project when they go outside of a prefab

## Build info

b6e01b9e3d13654c6849f1389767b459e7c5d6a3

## Steps To Reproduce

1. Create something that looks like this:
![image](https://user-images.githubusercontent.com/24578572/216560471-513e1446-f4b9-472a-886e-98d577fc2021.png)
2. Save the project
3. Load the project

The cable going from the midicontroller inside the prefab to outside the prefab will not load with the project.

## Expected vs. actual behavior

The midi controller connection should load regardless of whether it is inside or or outside a prefab. Right now, this only works if the midicontroller isn't inside the prefab.

**Comment by ThePython10110** [comment] 2023-02-04 19:01
Duplicate:
#723 
#946 
#654 
I think this probably happens because if you opened the prefab in a new project, and it didn't have `gain~gain`, Bespoke wouldn't know what to do with it.

You could always just disband the prefab.

**Comment by awwbees** [comment] 2023-02-05 04:42
duplicate of #946

**Closed as completed by awwbees** 2023-02-05 04:42 UTC
Labels: bug
