### ISSUE TITLE
drum sequencer grid notes not saved to preset module

### ISSUE THREAD

**Issue by boonier** [BespokeSynth/BespokeSynth#337] opened 2021-10-04 14:23 UTC
but the other controls are saved

**Comment by NoxyNixie** [comment] 2023-01-25 18:24
I believe this has been resolved in the latest Nightly builds and I'm unable to reproduce it.

![BespokeSynth_20230125_192232](https://user-images.githubusercontent.com/211381/214649777-468562ea-0482-4ff2-96d1-1c69151b41b3.gif)

**Closed as completed by NoxyNixie** 2023-01-25 18:24 UTC
Labels: bug
