### ISSUE TITLE
Bespoke crashes when I use the Snapshot's Blend function

### ISSUE THREAD

**Issue by nedrob** [BespokeSynth/BespokeSynth#1223] opened 2023-04-26 14:31 UTC
## Describe the bug
When I use the Snapshot's Blend function, Bespoke crashes as soon as I switch to another snapshot. Most times as soon as I click on a snapshot, Bespoke crashes right away. 

I am running on an M1 Mac with Ventura 13.2.1.

If I run Bespoke in Rosetta mode, the crash does not happen. If I turn off Rosetta mode, the crash happens all the time. 

## Build info

Nightly 1.1.0 (Apr 7, 2023)

## Steps To Reproduce
1. Load a NoteTable
2. Add a snapshot module and connect it to the notetable
3. Add notes to the notetable and save a snapshot.
4. change the notes and save another snapshot.
5. Set Snapshot's Blend to greater than 0
6. Change to another snapshot. Crash will happen either right away or after a few notes have blended to the new snapshot. 

## Expected vs. actual behavior
Bespoke should not crash. It should morph (or Blend) the notes to the new shapshot.

**Comment by PowerUser64** [comment] 2023-06-26 03:59
I can't reproduce this with the latest commit. Is this still an issue? It could be specific to arm builds.

**Comment by nedrob** [comment] 2023-06-26 04:53
Not sure, it's been awhile since I've downloaded a new version.

**Comment by PowerUser64** [comment] 2023-06-27 20:34
I'm going to close this for now, but feel free to re-open it if you encounter this again.

**Closed as completed by PowerUser64** 2023-06-27 20:34 UTC
Labels: bug, mystery
