### ISSUE TITLE
Bespoke crashing when running old patches

### ISSUE THREAD

**Issue by AbelianTransitSystem** [BespokeSynth/BespokeSynth#1410] opened 2023-08-19 03:39 UTC
## Describe the bug

Bespoke will not run for more than a few minutes without crashing

## Build info

bespoke NIGHTLY 1.2.0 (Jul 16 2023 02:57:59) - Windows 10 - HEAD 7c8094e

## Steps To Reproduce

Only requirement is that I open a previously created patch and wait a few minutes; inevitably it crashes

## Expected vs. actual behavior

See above
[crash_2023-08-18_23-35.txt](https://github.com/BespokeSynth/BespokeSynth/files/12384959/crash_2023-08-18_23-35.txt)

**Comment by KottV** [comment] 2023-08-19 21:55
Can you share that patch?

**Comment by AbelianTransitSystem** [comment] 2023-08-19 22:30
Certainly:
[Perfected Output.zip](https://github.com/BespokeSynth/BespokeSynth/files/12386788/Perfected.Output.zip)

**Comment by AbelianTransitSystem** [comment] 2023-08-19 22:31
While this is an example of a patch where this behavior occurs, this does not happen **only**  with this patch: it appears to be any patch created prior to the 1.2 release.

**Comment by NoxyNixie** [comment] 2023-08-20 04:24
I believe this is fixed in the latest Nightly build with #1379.

Also Duplicate of #1376.

**Closed as completed by NoxyNixie** 2023-08-20 04:24 UTC
Labels: bug, duplicate

**Comment by AbelianTransitSystem** [comment] 2023-08-20 14:12
Seems to be working as expected now, thank you!
