### ISSUE TITLE
1.2.1: error: only virtual member functions can be marked 'override'

### ISSUE THREAD

**Issue by yurivict** [BespokeSynth/BespokeSynth#1465] opened 2023-11-13 17:52 UTC
## Describe the bug
Build breaks:

```
/usr/ports/audio/bespokesynth/work/BespokeSynth-616ad67/Source/MainComponent.cpp:167:47: error: only virtual member functions can be marked 'override'
                              int numSamples) override
                                              ^~~~~~~~
1 error generated.
```

## Build info

FreeBSD 13.2
clang-16

**Comment by NoxyNixie** [comment] 2023-11-14 00:05
I believe this only happens if you compile against the incorrect version of JUCE. Bespoke 1.2.1 requires exactly JUCE 7.0.6. Not older and not newer.

Also this seems to be a duplicate of: #1047 (though with slightly different versions).

**Closed as completed by NoxyNixie** 2023-11-14 00:05 UTC
Labels: bug, duplicate

**Comment by yurivict** [comment] 2023-11-14 01:43
@NoxyNixie 

The same error occurs with juce-7.0.6.

```
/usr/ports/audio/bespokesynth/work/BespokeSynth-616ad67/Source/MainComponent.cpp:167:47: error: only virtual member functions can be marked 'override'
                              int numSamples) override
                                              ^~~~~~~~
1 error generated.
```
```
$ pkg info | grep juce
juce706-7.0.6                  C++ application framework to develop desktop and mobile applications
```

juce-7.0.6 never defines a virtual function audioDeviceIOCallback in any of its classes.

**Comment by KottV** [comment] 2023-11-14 02:07
could you provide cmake configure options and it's output?

**Comment by yurivict** [comment] 2023-11-14 02:08
bin/mkdir -p /usr/ports/audio/bespokesynth/work/.build
cd /usr/ports/audio/bespokesynth/work/.build; /usr/bin/env PKG_CONFIG=pkgconf PYTHON="/usr/local/bin/python3.9" XDG_DATA_HOME=/usr/ports/audio/bespokesynth/work  XDG_CONFIG_HOME=/usr/ports/audio/bespokesynth/work  XDG_CACHE_HOME=/usr/ports/audio/bespokesynth/work/.cache  HOME=/usr/ports/audio/bespokesynth/work PATH=/usr/local/libexec/ccache:/usr/ports/audio/bespokesynth/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin PKG_CONFIG_LIBDIR=/usr/ports/audio/bespokesynth/work/.pkgconfig:/usr/local/libdata/pkgconfig:/usr/local/share/pkgconfig:/usr/libdata/pkgconfig SHELL=/bin/sh CONFIG_SHELL=/bin/sh CMAKE_PREFIX_PATH="/usr/local" CCACHE_DIR="/tmp/.ccache" /usr/local/bin/cmake -DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -DNDEBUG"  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -DJUCE_INCLUDE_PNGLIB_CODE=0 -isystem /usr/local/include "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -DJUCE_INCLUDE_PNGLIB_CODE=0 -isystem /usr/local/include "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -DJUCE_INCLUDE_PNGLIB_CODE=0 -isystem /usr/local/include  -DNDEBUG"  -DCMAKE_EXE_LINKER_FLAGS:STRING=" -lpng -fstack-protector-strong -L/usr/local/lib "  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" -lpng -fstack-protector-strong -L/usr/local/lib "  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" -lpng -fstack-protector-strong -L/usr/local/lib "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON  -DFETCHCONTENT_FULLY_DISCONNECTED:BOOL=ON -DBESPOKE_SYSTEM_JUCE:BOOL=ON -DBESPOKE_SYSTEM_PYBIND11:BOOL=ON -DBESPOKE_SYSTEM_JSONCPP:BOOL=ON -DPython_ADDITIONAL_VERSIONS=3.9 -DPython_EXECUTABLE:FILEPATH="/usr/local/bin/python3.9" -DPython3_EXECUTABLE:FILEPATH="/usr/local/bin/python3.9" -DBOOST_PYTHON_SUFFIX:STRING=39 /usr/ports/audio/bespokesynth/work/BespokeSynth-616ad67
-- The C compiler identification is Clang 16.0.6
-- The CXX compiler identification is Clang 16.0.6
-- The ASM compiler identification is Clang with GNU-like command-line
-- Found assembler: /usr/local/libexec/ccache/cc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/libexec/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/libexec/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build Type: Release
-- Targeting 64 bit configuration
-- Found Python: /usr/local/bin/python3.9 (found version "3.9.18") found components: Interpreter Development Development.Module Development.Embed 
-- Python version: 3.9.18
-- Python executable: /usr/local/bin/python3.9
-- Python library: /usr/local/lib/libpython3.9.so
-- Using system provided JUCE
-- Found PkgConfig: /usr/local/bin/pkgconf (found version "2.0.3") 
-- Checking for module 'libcurl'
--   Found libcurl, version 8.4.0
-- Checking for modules 'webkit2gtk-4.0;gtk+-x11-3.0'
--   Found webkit2gtk-4.0, version 2.34.6
--   Found gtk+-x11-3.0, version 3.24.34
-- Checking for module 'alsa'
--   Found alsa, version 1.2.10
-- Checking for module 'freetype2'
--   Found freetype2, version 26.0.20
-- Checking for module 'gl'
--   Found gl, version 1.2
-- Checking for one of the modules 'jsoncpp'
-- Using system provided jsoncpp
-- PlayStation Move support disabled
-- Checking for module 'libusb-1.0'
--   Found libusb-1.0, version 1.0.13
-- Ableton Push 2 support enabled
-- Using system installed pybind11
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Performing Test HAS_FLTO_THIN
-- Performing Test HAS_FLTO_THIN - Success
-- Found pybind11: /usr/local/include (found version "2.11.1")
-- Using bundled tuning-library
-- Configuring done (9.6s)
-- Generating done (0.1s)
CMake Warning:
  Manually-specified variables were not used by the project:

    BOOST_PYTHON_SUFFIX
    CMAKE_MODULE_LINKER_FLAGS
    CMAKE_SHARED_LINKER_FLAGS
    FETCHCONTENT_FULLY_DISCONNECTED
    Python3_EXECUTABLE
    Python_ADDITIONAL_VERSIONS
    THREADS_HAVE_PTHREAD_ARG


-- Build files have been written to: /usr/ports/audio/bespokesynth/work/.build

**Comment by KottV** [comment] 2023-11-14 02:19
are you sure it grabs the correct JUCE ?
`grep -m1 "JUCE-" /usr/ports/audio/bespokesynth/work/.build/Source/Makefile`
did you try to build without `-DBESPOKE_SYSTEM_JUCE:BOOL=ON` ?

**Comment by yurivict** [comment] 2023-11-14 02:37
> are you sure it grabs the correct JUCE ?

Yes, I downgraded the juce version to 7.0.6.

```
$ grep -m1 "JUCE-" /usr/ports/audio/bespokesynth/work/.build/Source/Makefile
usr/local/include/JUCE-7.0.6/modules/juce_audio_basics/juce_audio_basics.o: usr/local/include/JUCE-7.0.6/modules/juce_audio_basics/juce_audio_basics.cpp.o
```

**Comment by yurivict** [comment] 2023-11-14 02:38
> did you try to build without -DBESPOKE_SYSTEM_JUCE:BOOL=ON ?

It would probably be downloading JUCE which isn't allowed during the build.

**Comment by KottV** [comment] 2023-11-14 03:01
> > did you try to build without -DBESPOKE_SYSTEM_JUCE:BOOL=ON ?
> 
> It would probably be downloading JUCE which isn't allowed during the build.

you can build it locally just for check if it's Bespoke/JUCE problem

I tested it with clang++-16 and there is no such error.
And I think it either you have an old BespokeSynth source prior this commit https://github.com/BespokeSynth/BespokeSynth/commit/8c1e6a6d0aa2c5ae2fb41340a50acf6c7daf6c4f or you're using wrong/broken JUCE.

**Comment by KottV** [comment] 2023-11-14 03:07
according this string in your command `/usr/ports/audio/bespokesynth/work/BespokeSynth-616ad67` you're trying to compile the code at this commit https://github.com/BespokeSynth/BespokeSynth/commit/616ad67c9c7b693aeb4a5cb19d8811baff99854c

**Comment by yurivict** [comment] 2023-11-14 08:04
Sorry, my bad.
The port was pinned to the wrong git hash.
It builds fine now.
