### ISSUE TITLE
prefab selection and movement causing crashes

### ISSUE THREAD

**Issue by cmovvv** [BespokeSynth/BespokeSynth#274] opened 2021-09-26 18:11 UTC
if you highlight a prefab along with other modules and try to move them all together, bespoke will either crash completely or delete the prefab and modules that were selected. i'll capture this behavior and post it shortly.

**Comment by cmovvv** [comment] 2021-09-26 18:16
here is a demo of the bug [https://youtu.be/x-ejSCwuTbA](https://youtu.be/x-ejSCwuTbA)

**Comment by cmovvv** [comment] 2021-09-26 18:20
[crash_2021-09-20_11-02.txt](https://github.com/BespokeSynth/BespokeSynth/files/7231983/crash_2021-09-20_11-02.txt)

**Comment by cassaundra** [comment] 2021-09-27 04:01
Hmm. I can reproduce on 1.0.0, but this seems to have been fixed by head. Are you able to compile from source, and if so, can you still reproduce the crash?

**Comment by awwbees** [comment] 2021-11-02 03:46
can't reproduce, might have been fixed by #532 or earlier

**Closed as completed by awwbees** 2021-11-02 03:46 UTC
