### ISSUE TITLE
Layout saved with 2 MIDI prefabs lose their assignations

### ISSUE THREAD

**Issue by nay-seven** [BespokeSynth/BespokeSynth#723] opened 2022-01-15 13:14 UTC
## Describe the bug

I create 2 prefabs with MIDI assignations, works perfectly when i reload them. 
Now if i create a layout with these 2 ones and save, when i reload, assignations are lost in the prefabs. if i disband them and save the layout, works fine

## Build info

bespoke NIGHTLY 1.1.0 (Jan 14 2022 04:02:55) - Mac OSX 10.14.6 - HEAD dd3fb7d

find the 2 prefabs+ buggy state attached

Thanks

[Prefabs+save state.zip](https://github.com/BespokeSynth/BespokeSynth/files/7875021/Prefabs%2Bsave.state.zip)

**Comment by ThePython10110** [comment] 2022-10-21 16:46
This still happens now, unfortunately.
I just created an issue before noticing this one.
bespoke NIGHTLY 1.1.0 (Sep 13 2022 00:30:04) - Windows 10 - HEAD 0acb8eb

**Comment by awwbees** [comment] 2023-02-05 04:42
duplicate of #946

**Closed as completed by awwbees** 2023-02-05 04:42 UTC
Labels: bug
