### ISSUE TITLE
deleting modules that were removed from a prefab doesn't update their targettedness

### ISSUE THREAD

**Issue by hannalambda** [BespokeSynth/BespokeSynth#191] opened 2021-09-19 05:41 UTC
as illustrated here 

![problem](https://user-images.githubusercontent.com/5291847/133916700-f396ce6c-0fdc-45d3-9e06-8f09ad6550bf.png)

**Comment by NoxyNixie** [comment] 2024-10-24 13:38
I believe this was fixed in 45472577d98039e7e363c2c232634334391b1350. I can't reproduce this in the latest Nightly build.

**Closed as completed by NoxyNixie** 2024-10-24 13:38 UTC
