### ISSUE TITLE
Missing First Note (in more than one place)

### ISSUE THREAD

**Issue by everythingability** [BespokeSynth/BespokeSynth#907] opened 2022-08-28 12:43 UTC
When you use a notesequencer, the first note - if it's the first note ever... as in you've just clicked "Play" doesn't play.

This often happens if you use a radiosequencers -> groupcontrol -> notesequencers combo ... as using a radio sequencer to turn on/off different parts of a song.

**Comment by NoxyNixie** [comment] 2022-08-31 01:41
Duplicate of: #759

**Closed as completed by NoxyNixie** 2022-08-31 01:41 UTC
Labels: bug, duplicate
