### ISSUE TITLE
many original project demo files are crashing Bespoke

### ISSUE THREAD

**Issue by drxian** [BespokeSynth/BespokeSynth#1394] opened 2023-07-29 12:26 UTC
## Describe the bug

many original project demo files are crashing Bespoke

## Build info

bespoke 1.2.0 (Jul 13 2023 20:02:13) - Windows 11 - HEAD b69c3fb

## Steps To Reproduce

open>defaul bespoke project directory>example__arpeggiation.bsk

## Expected vs. actual behavior

BEspoke crashes instead of opening the project file..

**Comment by NoxyNixie** [comment] 2023-07-31 01:56
Duplicate of #1376.

**Closed as completed by NoxyNixie** 2023-07-31 01:56 UTC
Labels: bug, duplicate

**Comment by unfa** [comment] 2023-08-17 08:24
Yeah, I wanted to try the example projects yesterday using recent alpha and Bespoke crashed right away :P
