### ISSUE TITLE
Vital Crash

### ISSUE THREAD

**Issue by SnakeZzzzz** [BespokeSynth/BespokeSynth#1171] opened 2023-02-19 12:49 UTC
Bespokesynth is closed when vital plugin is added and click "open"

**Comment by KottV** [comment] 2023-02-19 13:37
OS, version, etc ...

**Comment by NoxyNixie** [comment] 2023-02-19 14:20
Make sure you are opening the 64bit version of Vital.

Do you have a crashlog (they can be found in `Documents/BespokeSynth`)?

**Comment by SnakeZzzzz** [comment] 2023-02-20 06:19
Yes, Mac OS, Ventura 13.1.

The crash report:
backtrace:
0   BespokeSynth                        0x0000000108932c60 _ZN4juce11SystemStats17getStackBacktraceEv + 64
1   BespokeSynth                        0x00000001083353d2 _ZN12ModularSynth9DumpStatsEbPv + 482
2   BespokeSynth                        0x0000000108932e7d _ZN4juceL11handleCrashEi + 13
3   libsystem_platform.dylib            0x00007ff81ac03c1d _sigtramp + 29
4   libsystem_c.dylib                   0x00007ff85e5105f0 __c_locale + 0
5   libc++abi.dylib                     0x00007ff81ab942a1 _ZNK10__cxxabiv121__vmi_class_type_info16search_below_dstEPNS_19__dynamic_cast_infoEPKvib + 571
6   libc++abi.dylib                     0x00007ff81ab93d84 __dynamic_cast + 173
7   Vital                               0x0000000116f4b739 _ZN15RenderComponent8getValueEj + 297
8   Vital                               0x0000000116ef5ff4 _ZN19ScrollableComponent7resizedEv + 36
9   Vital                               0x0000000116f0ca9f _ZN10TextEditor7resizedEv + 15
10  Vital                               0x0000000116c74984 _ZN4juce9Component24sendMovedResizedMessagesEbb + 196
11  Vital                               0x0000000116efc915 _ZN6Slider7resizedEv + 101
12  Vital                               0x0000000116c74984 _ZN4juce9Component24sendMovedResizedMessagesEbb + 196
13  Vital                               0x0000000116d9e3ae _ZN11BendSection7resizedEv + 158
14  Vital                               0x0000000116c74984 _ZN4juce9Component24sendMovedResizedMessagesEbb + 196
15  Vital                               0x0000000116dc960a _ZN13FullInterface7resizedEv + 986
16  Vital                               0x0000000116c74984 _ZN4juce9Component24sendMovedResizedMessagesEbb + 196
17  Vital                               0x0000000116d1604c _ZN11SynthEditor13editorResizedEv + 156
18  Vital                               0x0000000116ed529b _ZN12PluginEditorC2EP20ApplicationProcessor + 827
19  Vital                               0x0000000116ed7f42 _ZN20ApplicationProcessor12createEditorEv + 34
20  Vital                               0x0000000116b8d640 _ZN6JuceAU19JuceUICreationClass18uiViewForAudioUnitEP11objc_objectP13objc_selectorP23ComponentInstanceRecord6CGSize + 160
21  BespokeSynth                        0x0000000108877a72 _ZN4juce26AudioUnitPluginWindowCocoa10createViewEb + 450
22  BespokeSynth                        0x00000001088775e6 _ZN4juce26AudioUnitPluginWindowCocoaC2ERNS_23AudioUnitPluginInstanceEb + 262
23  BespokeSynth                        0x0000000108841047 _ZN4juce23AudioUnitPluginInstance12createEditorEv + 39
24  BespokeSynth                        0x0000000108811304 _ZN4juce14AudioProcessor20createEditorIfNeededEv + 84
25  BespokeSynth                        0x000000010871a1d9 _ZN9VSTWindow15CreateVSTWindowEP9VSTPluginNS_16WindowFormatTypeE + 89
26  BespokeSynth                        0x00000001086fff17 _ZN9VSTPlugin4PollEv + 695
27  BespokeSynth                        0x00000001082b3ee3 _ZN15IDrawableModule8BasePollEv + 19
28  BespokeSynth                        0x00000001084f55fc _ZN15ModuleContainer4PollEv + 60
29  BespokeSynth                        0x0000000108337c6f _ZN12ModularSynth4PollEv + 367
30  BespokeSynth                        0x000000010830846e _ZN20MainContentComponent13timerCallbackEv + 126
31  BespokeSynth                        0x00000001089d862e _ZN4juce5Timer11TimerThread10callTimersEv + 222
32  BespokeSynth                        0x00000001089dbf74 _ZN4juce12MessageQueue18deliverNextMessageEv + 52
33  BespokeSynth                        0x00000001089dbeee _ZN4juce12MessageQueue15runLoopCallbackEv + 14
34  CoreFoundation                      0x00007ff81acb4b98 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
35  CoreFoundation                      0x00007ff81acb4b47 __CFRunLoopDoSource0 + 157
36  CoreFoundation                      0x00007ff81acb4921 __CFRunLoopDoSources0 + 212
37  CoreFoundation                      0x00007ff81acb359b __CFRunLoopRun + 929
38  CoreFoundation                      0x00007ff81acb2b80 CFRunLoopRunSpecific + 560
39  HIToolbox                           0x00007ff8245f7766 RunCurrentEventLoopInMode + 292
40  HIToolbox                           0x00007ff8245f7576 ReceiveNextEventCommon + 679
41  HIToolbox                           0x00007ff8245f72b3 _BlockUntilNextEventMatchingListInModeWithFilter + 70
42  AppKit                              0x00007ff81ddfef33 _DPSNextEvent + 909
43  AppKit                              0x00007ff81ddfddb4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1219
44  AppKit                              0x00007ff81ddf03f7 -[NSApplication run] + 586
45  BespokeSynth                        0x00000001089cfc04 _ZN4juce19JUCEApplicationBase4mainEv + 164
46  BespokeSynth                        0x00000001089cfb13 _ZN4juce19JUCEApplicationBase4mainEiPPKc + 83
47  dyld                                0x00007ff81a8a6310 start + 2432



OS: Mac OSX 13.1
CPU vendor: GenuineIntel
CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
CPU speed: 1400 MHz
num cores: 8
num CPUs: 4
RAM: 8192 MB
computer: Pablos-MacBook-Pro
language: es
region: ES
display language: es-ES
description: MacBookPro15,4
manufacturer: Apple
build: bespoke NIGHTLY 1.1.0 (Feb 17 2023 05:03:44))

**Comment by NoxyNixie** [comment] 2023-02-20 15:55
This crash is in Vital itself. I don't think this can be fixed in Bespoke.

Al I can suggest is to update or downgrade your Vital to try and get a version that does work and report this crash to Vital's bug forum: https://forum.vital.audio/c/bugs/6

There is already a similar issue here: https://forum.vital.audio/t/vital-1-5-x-crashes-while-opening-its-gui/10714

Also I can't reproduce this issue since Vital 1.5.5 works great on my system.

**Closed as completed by NoxyNixie** 2023-02-20 15:55 UTC
