### ISSUE TITLE
Bug - examples crash the application

### ISSUE THREAD

**Issue by dehesselle** [BespokeSynth/BespokeSynth#1390] opened 2023-07-23 18:49 UTC
## Describe the bug

Trying to load any of the examples crashes the application.

## Build info

bespoke 1.2.0 (Jul 13 2023 20:02:13) - Windows 10 - HEAD b69c3fb

## Steps To Reproduce

- open the application
- click load
- select `example_arpeggiation.bsk`
- crash

## Expected vs. actual behavior

I expect the provided examples to load and not crash the application.

**Comment by NoxyNixie** [comment] 2023-07-24 21:37
Duplicate of #1376.

**Closed as completed by NoxyNixie** 2023-07-24 21:37 UTC
Labels: bug, duplicate
