### ISSUE TITLE
module "presets" doesn't work on module "dumsequencer"

### ISSUE THREAD

**Issue by rerry1234** [BespokeSynth/BespokeSynth#652] opened 2021-11-26 19:06 UTC
module "presets" doesn't work on module "dumsequencer".
sequences are not saved in presets.

which does work in "notesequencer".

**Comment by rerry1234** [comment] 2021-11-26 19:14
also, doesn't save sequences on "controlsequencer"

**Comment by NoxyNixie** [comment] 2023-01-25 23:24
I believe this has been resolved in the latest Nightly builds and I'm unable to reproduce it.

![BespokeSynth_20230125_192232](https://user-images.githubusercontent.com/211381/214649777-468562ea-0482-4ff2-96d1-1c69151b41b3.gif)
![BespokeSynth_20230126_002336](https://user-images.githubusercontent.com/211381/214715718-9a8cc716-6e0d-4504-a6d4-03b06726c16a.gif)

**Closed as completed by NoxyNixie** 2023-01-25 23:24 UTC
