### ISSUE TITLE
mult and add don't save/load correctly

### ISSUE THREAD

**Issue by disconex** [BespokeSynth/BespokeSynth#231] opened 2021-09-22 09:22 UTC
It is sometimes desirable to connect only one input of a `mult` or `add` and use the other slider to set a constant.

![Screen Shot 2021-09-22 at 10 54 19](https://user-images.githubusercontent.com/90849955/134317514-0dff0a67-8625-4d67-9d04-69dfc0e76007.png)

In this contrived example, a modulation signal is transformed from the range (−1, 1) to the range (0, 0.8). To make this work, the ranges of the top sliders of the `mult` and `add` modules were expanded to start at −1; the bottom sliders are set to 0.4.

![Screen Shot 2021-09-22 at 11 02 46](https://user-images.githubusercontent.com/90849955/134317581-118f0b03-a063-4238-82d0-1944f53d83d7.png)

Upon saving and loading the patch, the ranges of the sliders are reset to their defaults, and the second value of the `mult` is reset to 0; the `macroslider` is receiving an incorrect value.

**Comment by NoxyNixie** [comment] 2023-01-24 20:51
I think this may have been resolved since I am unable to reproduce this bug in the latest Nightly build (I tried to be as close to your example as possible):
![image](https://user-images.githubusercontent.com/211381/214409336-55c72427-9264-4920-a3c2-adf8c4b75ac4.png)

This is after closing Bespoke and loading the savestate again.

If this problem returns please don't hesitate to create a new issue ;)

**Closed as completed by NoxyNixie** 2023-01-24 20:51 UTC
Labels: bug
