### ISSUE TITLE
Scripting example crashes on load on windows 10

### ISSUE THREAD

**Issue by JTriggerFish** [BespokeSynth/BespokeSynth#239] opened 2021-09-22 20:27 UTC
[crash_2021-09-22_21-25.txt](https://github.com/awwbees/BespokeSynth/files/7213569/crash_2021-09-22_21-25.txt)

**Comment by tobtobxx** [comment] 2021-09-22 20:38
Duplicate of #129.

**Closed as completed** 2021-09-22 22:12 UTC
