### ISSUE TITLE
Add Block and Mult Block values seem to swap or reset on save

### ISSUE THREAD

**Issue by lapraswastaken** [BespokeSynth/BespokeSynth#166] opened 2021-09-17 20:16 UTC
After saving my project and reopening it, the values in my math Blocks seem to have been switched around or reset. I'm on Windows 10, and I'm using the 1.0.0 build.

Here's my setup, where a slider has two different cc values for a HSB and an LSB. I'm routing the slider's HSB, that outputs values 0 to 1 (and is offset by 0.004 for some reason), to an Add Block that puts it into the range -0.5 to -.5 and adding that to a second Add Block; and then taking the slider's LSB, that outputs values 0 to 1, and multiplying it by 0.01 before adding it to the second Add Block.

This is what it looks like before saving and loading.

![image](https://user-images.githubusercontent.com/63134341/133848346-667f25e8-822a-427b-b3fd-efc52c1934ed.png)

This is what it looks like after saving and loading. The Mult Block seems to have its 2nd value reset to 0. I couldn't manage to reproduce what happens to the HSB's first Add Block, but sometimes that resets to 0 as well. My current workaround is adding a Value Setter Block to each.

![image](https://user-images.githubusercontent.com/63134341/133847899-69c2399b-1f91-45d0-b707-12f803d44a4a.png)

**Comment by NoxyNixie** [comment] 2023-01-24 18:44
I can't reproduce this issue. The following works perfectly even after reloads:
![image](https://user-images.githubusercontent.com/211381/214380370-6c7acb6d-d9cc-4cfe-b6ff-a7ebaddf7fbe.png)

There have been quite a few fixes since 1.0.0 and I know of a few modulation related changes so this may have been fixed in those.

One of the things I do notice is that some of your modules still have the same name (`add` and `add`) this is no longer possible and could be causing your issues.

If you can reproduce this in the latest Nightly build please feel free to report back here in this issue or in a new one ;)

**Closed as completed by NoxyNixie** 2023-01-24 18:44 UTC
